name: Android CI

on:
  push:
    branches: [ main ]       # Запускать при пуше в ветку main
  pull_request:
    branches: [ main ]       # И при открытии pull request

jobs:
  build:
    runs-on: ubuntu-latest    # GitHub создаёт виртуальную машину с Linux (Ubuntu)

    steps:
      # 1️⃣ Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Ставим нужную Java (у тебя Java 11)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'   # официальная реализация OpenJDK
          java-version: '17'
          cache: gradle             # кэшируем зависимости Gradle

      # 3️⃣ Делаем Gradle исполняемым
      - name: Make Gradle executable
        run: chmod +x gradlew

      # 4️⃣ Скачиваем зависимости и собираем проект
      - name: Build with AssembleDebug
        run: ./gradlew assembleDebug

      # 5️⃣ Запускаем unit-тесты
        # - name: Run tests
      # run: ./gradlew test

      # 6️⃣ Проверяем линтер (если есть)
        # - name: Run lint
      # run: ./gradlew lint /*
